#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);
use File::Basename;
use File::Path;

foreach (qw(FaxNotify FaxDispatch))
{
    safe_symlink("/etc/e-smith/templates-default/template-begin-shell",
        "root/etc/e-smith/templates/var/spool/hylafax/etc/$_/template-begin");
}
safe_symlink("/etc/e-smith/templates-default/template-begin-shell", "root/etc/e-smith/templates/etc/cron.daily/hylafax/template-begin");


safe_symlink("/var/spool/hylafax/bin/ps2fax.gs", "root/var/spool/hylafax/bin/ps2fax");
safe_symlink("/var/spool/hylafax/bin/pdf2fax.gs", "root/var/spool/hylafax/bin/pdf2fax");


# Expand hosts.hfaxd

templates2events("/var/spool/hylafax/etc/hosts.hfaxd",
			qw(
				interface-update
				trusted-networks-modify
			));


#--------------------------------------------------
# actions for nethserver-hylafax-update event
#--------------------------------------------------

my $event = "nethserver-hylafax-update";

event_actions($event, qw(
     initialize-default-databases 00
));

templates2events("/var/spool/hylafax/etc/config",$event);
templates2events("/var/spool/hylafax/etc/hosts.hfaxd",$event);
templates2events("/var/spool/hylafax/etc/FaxDispatch",$event);
templates2events("/var/spool/hylafax/etc/FaxNotify",$event);
templates2events("/var/spool/hylafax/etc/config.nethesis",$event);
templates2events("/etc/hylafax/hyla.conf",$event);
templates2events("/etc/cron.daily/hylafax",$event);

event_services($event, 'hylafax' => 'restart');


#--------------------------------------------------
# actions for nethserver-hylafax-save event
#--------------------------------------------------

$event = "nethserver-hylafax-save";

templates2events("/var/spool/hylafax/etc/config",$event);
templates2events("/var/spool/hylafax/etc/hosts.hfaxd",$event);
templates2events("/var/spool/hylafax/etc/FaxDispatch",$event);
templates2events("/var/spool/hylafax/etc/FaxNotify",$event);
templates2events("/var/spool/hylafax/etc/config.nethesis",$event);
templates2events("/etc/hylafax/hyla.conf",$event);
templates2events("/var/spool/hylafax/etc/dispatch/print.conf",$event);
templates2events("/etc/cron.daily/hylafax",$event);

event_actions($event,
             'nethserver-hylafax-modemsetup' => 20,
             'nethserver-hylafax-sambafax' => 20);

event_services($event, 'hylafax' => 'restart');

#--------------------------------------------------
# actions for migration-import event
#--------------------------------------------------

$event = "migration-import";
event_actions($event, 'nethserver-hylafax-migrate' => 70);
