#!/bin/bash

# logger -t FaxAccounting $@

date="$1"; shift
time="$2"; shift
ENTRYTYPE="$1"; shift
jobid="$1"; shift

DOCHOME=/var/lib/nethserver/fax/docs

# logger -t FaxAccounting entrytype = $ENTRYTYPE

case $ENTRYTYPE in
"UNSENT")
;;
"SEND")
;;
"RECV")
	FILENAME=`echo $jobid | cut -d'/' -f2`
	FILENAME=`echo $FILENAME | cut -d'.' -f1`
	FILE=/var/spool/hylafax/recvq/$FILENAME.tif
	
	if [ -f $FILE ]; then
		cp $FILE $DOCHOME/received/; chmod 666 $DOCHOME/received/$FILENAME.tif
	fi
;;

"SUBMIT")
	FAX_RPATH='/sent'
	pathsent=$FAX_RPATH

	# === Saving file === #
	File=''
	File=`grep '^[!]*pdf' /var/spool/hylafax/sendq/q$jobid | cut -d ':' -f4`
	if [ -z $File ]; then
		File=`grep '^[!]*tiff' /var/spool/hylafax/sendq/q$jobid | cut -d ':' -f4`
	fi
	if [ -z $File ]; then
		File=`grep '^[!]*postscript' /var/spool/hylafax/sendq/q$jobid | cut -d ':' -f4`
	fi
	File_dest=`echo $File | cut -d'.' -f1,2`
	File_dest=`basename $File_dest`
	File="/var/spool/hylafax/$File"
	# logger -t FaxAccounting "cp $File $DOCHOME$pathsent/$File_dest" 
        if [ ! -z $File ] && [ -f $File ] && [ ! -f "$DOCHOME$pathsent/$File_dest" ]; then       #check if sent file is empty
		cp $File "$DOCHOME$pathsent/$File_dest" && chmod 666 "$DOCHOME$pathsent/$File_dest"
	else
		logger -t FaxAccounting "Can't save sent file (jobid: $jobid) -> $File"
	fi
;;

*)
	exit 0
;;

esac
