#!/bin/bash

# logger -t FaxAccounting $@

date="$1"; shift
time="$2"; shift
ENTRYTYPE="$1"; shift
jobid="$1"; shift
shift
FILENAME=$1

DOCHOME=/var/lib/nethserver/fax/docs

# logger -t FaxAccounting entrytype = $ENTRYTYPE

case $ENTRYTYPE in
"UNSENT")
;;
"SEND")
;;
"RECV")
	FILE=$(basename $FILENAME)
        cp $FILENAME $DOCHOME/received/ && chmod 666 $DOCHOME/received/$FILE
;;

"SUBMIT")
	FAX_RPATH='/sent'
	pathsent=$FAX_RPATH

	# === Saving file === #
	File=''
	File=`grep '^[!]*pdf' /var/spool/hylafax/sendq/q$jobid | cut -d ':' -f4`
	extension=pdf
	if [ -z $File ]; then
		File=`grep '^[!]*tiff' /var/spool/hylafax/sendq/q$jobid | cut -d ':' -f4`
		extension=tif
	fi
	if [ -z $File ]; then
		File=`grep '^[!]*postscript' /var/spool/hylafax/sendq/q$jobid | cut -d ':' -f4`
		extension=ps
	fi
	File_dest="$jobid.$extension"
	File="/var/spool/hylafax/$File"
	# logger -t FaxAccounting "cp $File $DOCHOME$pathsent/$File_dest" 
        if [ ! -z $File ] && [ -f $File ] && [ ! -f "$DOCHOME$pathsent/$File_dest" ]; then       #check if sent file is empty
		cp $File "$DOCHOME$pathsent/$File_dest" && chmod 666 "$DOCHOME$pathsent/$File_dest"
	fi
;;

*)
	exit 0
;;

esac
