#!/bin/bash
data="$1"; shift
ENTRYTYPE="$1"; shift
commid="$1"; shift
DEVICE="$1"; shift
jobid="$1"; shift
JOBTAG="$1"; shift
USERID="$1"; shift
number="$1"; shift
TSI="$1"; shift
PARAMS="$1"; shift
totpages="$1"; shift
JTIME="$1"; shift
CONNTIME="$1"; shift
faxstatus="$1"; shift
CIDNAME="$1"; shift
CIDNUMBER="$1"; shift
CALLID="$1"; shift
owner="$1"; shift
DCS="$1"; shift
JOBINFO="$1"; shift

totdials=`echo $JOBINFO | cut -d'/' -f4`
DOCHOME=/var/lib/nethserver/fax/docs

if [ "$faxstatus" != "" ] || [ "$ENTRYTYPE" == "UNSENT" ]; then
	state=8;
else
	state=7;
fi

if [ $JTIME == '' ]; then
    JTIME=0
fi


case $ENTRYTYPE in
"UNSENT")
;;
"SEND")
;;
"RECV")
	FILENAME=`echo $jobid | cut -d'/' -f2`
	FILENAME=`echo $FILENAME | cut -d'.' -f1`
	FILE=/var/spool/hylafax/recvq/$FILENAME.tif
	
	if [ -f $FILE ]; then
		cp $FILE $DOCHOME/received/; chmod 666 $DOCHOME/received/$FILENAME.tif
	fi
;;

"SUBMIT")
	FAX_RPATH='/sent'
	pathsent=$FAX_RPATH

	# === Saving file === #
	File=''
	File=`grep '^[!]*pdf' /var/spool/hylafax/sendq/q$jobid | cut -d ':' -f4`
	if [ -z $File ]; then
		File=`grep '^[!]*tiff' /var/spool/hylafax/sendq/q$jobid | cut -d ':' -f4`
	fi
	if [ -z $File ]; then
		File=`grep '^[!]*postscript' /var/spool/hylafax/sendq/q$jobid | cut -d ':' -f4`
	fi
	File_dest=`echo $File | cut -d'.' -f1,2`
	File_dest=`basename $File_dest`
	File="/var/spool/hylafax/$File"
	#logger -t DEBUG "cp $File $DOCHOME$pathsent/$File_dest" 
        if [ ! -z $File ] && [ -f $File ] && [ ! -f "$DOCHOME$pathsent/$File_dest" ]; then       #check if sent file is empty
		cp $File "$DOCHOME$pathsent/$File_dest" && chmod 666 "$DOCHOME$pathsent/$File_dest"
	else
		logger -t Hylfax "Can't save sent file (jobid: $jobid) -> $File"
	fi
;;

*)
	exit 0
;;

esac
