#!/usr/bin/perl -w


#----------------------------------------------------------------------
# copyright (C) 2010 Nethesis
#		
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#----------------------------------------------------------------------

use strict;
use Errno;

# create lp spool
system("/usr/sbin/checkpc -f >/dev/null") == 0
    or die("Error during checkpc. \n");

exit (0);


