#!/bin/sh


mysql faxdb -e "select fax_type from faxweb_fax limit 1" &> /dev/null && exit 0

rm -f /etc/e-smith/sql/init/10nethfaxweb.sql
ln -sf /var/spool/hylafax/db/faxdb2.sql \
       /etc/e-smith/sql/init/10nethfaxweb.sql

/etc/init.d/mysql.init start

/usr/bin/php /var/spool/hylafax/db/convert.php 

