#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l., based on a work oj Christian DUMONT (aka GLA).
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

package esmith;

use strict;
use Errno;
use File::Basename:
use esmith::config;
use esmith::util;
use esmith::db;

my $mabase;
my %conf;
tie %conf, 'esmith::config';

our $db = esmith::ConfigDB->open
          or die("Unable to open the configuration database. \n");

$mabase = $db->get('hylafax')
   or die("Unable to find Hylafax record in configuration database. \n");
my $FaxDevice           = $mabase->prop('FaxDevice');

# execute faxaddmodem only if not using iaxmodem
if ($FaxDevice ne 'iax') {
  system("/usr/sbin/neth-addmodem &> /var/log/addmodem.log") == 0
}


# stop all faxgetty-* services and remove relative files
my @files = </etc/event.d/faxgetty-*>
foreach $file (@files) {
   system("/sbin/stop ".basename($file));
   unlink($file);
} 

# create upstart file
my $upstart_file="/etc/event.d/faxgetty-$FaxDevice";
my $doc = <<END
start on runlevel 2
start on runlevel 3
start on runlevel 4
start on runlevel 5

stop on runlevel 0
stop on runlevel 1
stop on runlevel 6

respawn
exec /usr/sbin/faxgetty $FaxDevice
END

open (FILE, ">>$upstart_file"); 
print FILE $doc; 
close (FILE); 

# start new upstart file
system("/sbin/start faxgetty-$FaxDevice");
