#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::DB::db;
use esmith::event;
use NethServer::Migrate;
use File::Copy;
use strict;

my $event = shift;
my $sourceDir = shift;
my $esmithDbDir = '/home/e-smith/db';
my $faxDir = '/home/e-smith/fax/docs';
my $destDir = '/var/lib/nethserver/fax/docs';
my $errors = 0;
if( ! -d $sourceDir) {
    die("Could not find dir $sourceDir");
}

my $srcConfigDb = esmith::DB::db->open_ro(join('', $sourceDir, $esmithDbDir, '/configuration')) || die("Could not open source configuration database in $sourceDir \n");

my $dstConfigDb = esmith::DB::db->open('configuration') || die("Could not open destination account db\n");

# update e-smith db
my $service = 'hylafax';
my $old = $srcConfigDb->get($service);
my $new = $dstConfigDb->get($service) || $dstConfigDb->new_record($service);
$new->merge_props($old->props);
$new->delete_prop('Auth');

my $pname = $old->prop('PrinterName') || '';
if ($pname eq '') {
    $new->set_prop('PrintReceived','disabled');
} else {
    $new->set_prop('PrintReceived','enabled');
}

# copy fax files
NethServer::Migrate::migrateDir("$sourceDir/$faxDir/sent","$destDir/sent");
NethServer::Migrate::migrateDir("$sourceDir/$faxDir/received","$destDir/received");
mkdir("$destDir/sentm");
NethServer::Migrate::migrateDir("$sourceDir/$faxDir/sentm","$destDir/sentm");

# copy seqf
copy("$sourceDir/home/e-smith/hylafax/log/seqf",'/var/spool/hylafax/log/seqf ');
copy("$sourceDir/home/e-smith/hylafax/sendq/seqf",'/var/spool/hylafax/sendq/seqf ');
copy("$sourceDir/home/e-smith/hylafax/docq/seqf",'/var/spool/hylafax/docq/seqf ');
NethServer::Migrate::migrateDir("$sourceDir/home/e-smith/hylafax/info","/var/spool/hylafax/info");
NethServer::Migrate::migrateDir("$sourceDir/home/e-smith/hylafax/recvq","/var/spool/hylafax/recvq");
my $configFiles = "$sourceDir/home/e-smith/hylafax/etc/config.*";
my @files = <$configFiles>;
foreach my $file (@files) {
    copy("$sourceDir/home/e-smith/hylafax/etc/$file","/var/spool/hylafax/etc/$file");
}

#
# Apply configuration
# 
if( ! esmith::event::event_signal('nethserver-hylafax-update')) {
    exit(1);
}

exit 0;
